name: stockify
description: Smart inventory & ordering platform for Kirana shops

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  provider: ^6.1.2
  google_fonts: ^6.2.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  uuid: ^4.4.0
  flutter_animate: ^4.5.0
  badges: ^3.1.2
  shimmer: ^3.0.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true




flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/logos.png"